// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfJKkvLgAwJT0EmGPElAxSXywX3x4V_1I',
    appId: '1:472759397512:web:884df0d6ed53a4f506033d',
    messagingSenderId: '472759397512',
    projectId: 'beta-learning-f75cb',
    authDomain: 'beta-learning-f75cb.firebaseapp.com',
    storageBucket: 'beta-learning-f75cb.appspot.com',
    measurementId: 'G-15TR6QY5JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLC_9TEYa_FRXj1kMXpxBFGOWZXoyYdd4',
    appId: '1:472759397512:android:2bb2bd2002962ff606033d',
    messagingSenderId: '472759397512',
    projectId: 'beta-learning-f75cb',
    storageBucket: 'beta-learning-f75cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Uv48vumR9a7VrFtylqpk7Z81NV7n5RA',
    appId: '1:472759397512:ios:c9e08de282c3ba5b06033d',
    messagingSenderId: '472759397512',
    projectId: 'beta-learning-f75cb',
    storageBucket: 'beta-learning-f75cb.appspot.com',
    iosClientId: '472759397512-urbg7k8plrlohffc8ua3bh3i9cvh18ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.jangalma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Uv48vumR9a7VrFtylqpk7Z81NV7n5RA',
    appId: '1:472759397512:ios:c9e08de282c3ba5b06033d',
    messagingSenderId: '472759397512',
    projectId: 'beta-learning-f75cb',
    storageBucket: 'beta-learning-f75cb.appspot.com',
    iosClientId: '472759397512-urbg7k8plrlohffc8ua3bh3i9cvh18ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.jangalma',
  );
}
