// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZom0HSXOhh0aM9exYs7YILToSvoMB9_8',
    appId: '1:416537931713:web:4827d41eee8b3aa97a0940',
    messagingSenderId: '416537931713',
    projectId: 'beta-jangalma',
    authDomain: 'beta-jangalma.firebaseapp.com',
    storageBucket: 'beta-jangalma.appspot.com',
    measurementId: 'G-MFVEV2QQS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNJ1HY3ba_UrWIpDtAxSUqmdlfDKdkOU',
    appId: '1:416537931713:android:1f915c6fc75d76d27a0940',
    messagingSenderId: '416537931713',
    projectId: 'beta-jangalma',
    storageBucket: 'beta-jangalma.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl53-uQuvw3Ev1WJOisC8SlSGNfYuBHVA',
    appId: '1:416537931713:ios:8c318939d89c65da7a0940',
    messagingSenderId: '416537931713',
    projectId: 'beta-jangalma',
    storageBucket: 'beta-jangalma.appspot.com',
    iosClientId: '416537931713-e0mevkflsjpgktfihu4nh8qehf904ef9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jangalma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl53-uQuvw3Ev1WJOisC8SlSGNfYuBHVA',
    appId: '1:416537931713:ios:8c318939d89c65da7a0940',
    messagingSenderId: '416537931713',
    projectId: 'beta-jangalma',
    storageBucket: 'beta-jangalma.appspot.com',
    iosClientId: '416537931713-e0mevkflsjpgktfihu4nh8qehf904ef9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jangalma',
  );
}
